apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
      instance: myapp-stable
  replicas: {{ .Values.stable.replicas }}
  template:
    metadata:
      labels:
        app: myapp
        instance: myapp-stable
    spec:
      containers:
      - name: myapp
        image: "{{ .Values.image }}:{{ .Values.stable.imageTag }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
        - containerPort: 8080
