apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apps-generic-chart.fullname" . }}
  labels:
    app: {{ template "apps-generic-chart.name" . }}
    chart: {{ template "apps-generic-chart.chart" . }}
    release: {{ .Release.Name }}
    release-revision: {{ .Release.Revision | quote }}
    {{- if .Values.branch }}
    branch: {{ .Values.branch | quote }}
    {{- end }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ template "apps-generic-chart.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        restart: {{ .Values.restart | quote }}
        app: {{ template "apps-generic-chart.name" . }}
        release: {{ .Release.Name }}
        {{- if .Values.AppGitCommit }}
        app-git-commit: {{ .Values.AppGitCommit }}
        {{- end }}
    spec:
      {{- if .Values.securityContext }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: docker-registry.tnt-digital.io
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- if .Values.container.ports }}
            {{- range .Values.container.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
              protocol: {{ .protocol }}
            {{- end }}
          {{- end }}
        {{- if .Values.healthChecks -}}
          {{- if .Values.healthChecks.livenessProbe }}
          livenessProbe:
{{ toYaml .Values.healthChecks.livenessProbe | indent 12 }}
          {{- end }}
          {{- if .Values.healthChecks.readinessProbe }}
          readinessProbe:
{{ toYaml .Values.healthChecks.readinessProbe | indent 12 }}
          {{- end }}
        {{- end }}
          env:
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
          {{- if .Values.java_app }}
            - name: JAVA_MEMORY
              value: "{{ sub .Values.memory_limit ( div (mul .Values.memory_limit .Values.memory_percent) 100 ) | default 256 }}m"
            - name: JAVA_XMX
              value: "{{ sub .Values.memory_limit ( div (mul .Values.memory_limit .Values.memory_percent) 100 ) | default 256 }}m"
            - name: JAVA_XMS
              value: "{{ sub .Values.memory_limit ( div (mul .Values.memory_limit .Values.memory_percent) 100 ) | default 256 }}m"
          {{- end }}
          {{- if .Values.extraVars }}
{{ toYaml .Values.extraVars | indent 12 }}
          {{- end }}
          {{- if .Values.extraVarsFrom }}
          envFrom:
{{ toYaml .Values.extraVarsFrom | indent 12 }}
          {{- end }}
          resources:
            limits:
          {{- if and .Values.resources .Values.resources.limits }}
              cpu: "{{ .Values.resources.limits.cpu | default 0.1 }}"
            {{- if .Values.java_app }}
              memory: "{{ .Values.memory_limit | default 512 }}Mi"
            {{- else }}
              memory: {{ .Values.resources.limits.memory | default "512Mi" }}
            {{- end }}
          {{- else }}
              cpu: "0.1"
              memory: 512Mi
          {{- end }}
            requests:
          {{- if and .Values.resources .Values.resources.requests }}
              cpu: "{{ .Values.resources.requests.cpu | default 0.1 }}"
            {{- if .Values.java_app }}
              memory: "{{ .Values.memory_limit | default 512 }}Mi"
            {{- else }}
              memory: {{ .Values.resources.requests.memory | default "512Mi" }}
            {{- end }}
          {{- else }}
              cpu: "0.1"
              memory: 512Mi
          {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
