{{- if and .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "apps-generic-chart.fullname" . }}
  labels:
    app: {{ template "apps-generic-chart.name" . }}
    chart: {{ template "apps-generic-chart.chart" . }}
    release: {{ .Release.Name }}
    release-revision: {{ .Release.Revision | quote }}
    {{- if .Values.branch }}
    branch: {{ .Values.branch | quote }}
    {{- end }}
    heritage: {{ .Release.Service }}
spec:
  endpoints:
    - honorLabels: true
      interval: 45s
      path: {{ .Values.serviceMonitor.path | default "/metrics" }}
      port: {{ .Values.serviceMonitor.port | default "http" }}
      metricRelabelings:
        - action: replace
          regex: (.*):.*
          replacement: ${1}
          sourceLabels:
            - instance
          targetLabel: instance
        {{- if .Values.serviceMonitor.metricRelabelings }}
{{ toYaml .Values.serviceMonitor.metricRelabelings | indent 4 }}
        {{- end }}
    {{- if .Values.serviceMonitor.extraEndpoints }}
{{ toYaml .Values.serviceMonitor.extraEndpoints | indent 2 }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      release: {{ .Release.Name }}
{{- end }}
