apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-ingress
spec:
  selector:
    matchLabels:
      app: myapp-ingress
      instance: myapp-ingress-stable
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: myapp-ingress
        instance: myapp-ingress-stable
    spec:
      containers:
      - name: myapp-ingress
        image: "{{ .Values.image }}:{{ .Values.stable.imageTag }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
        - containerPort: 8080