apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp-ingress
  labels:
    release: myapp-ingress
spec:
  selector:
    matchLabels:
      app: myapp-ingress
  endpoints:
  - port: metrics