# Template to manage multiple Ingress Rules
{{- range $i_key, $i_val := .Values.ingress -}}
{{- if and ($i_val.enabled) (or (ne $i_val.host "") (ne $i_val.clusterFqdn "")) }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "apps-generic-chart.fullname" $ }}-{{ $i_key }}
  labels:
    app: {{ template "apps-generic-chart.name" $ }}
    chart: {{ template "apps-generic-chart.chart" $ }}
    release: {{ $.Release.Name }}
    release-revision: {{ $.Release.Revision | quote }}
    {{- if $.Values.branch }}
    branch: {{ $.Values.branch | quote }}
    {{- end }}
    heritage: {{ $.Release.Service }}
  annotations:
    # This allow us pass templates with values for annotation and evaluate them here using `tpl` functionality
    {{- range $a_key, $a_val := $i_val.annotations }}
    {{ $a_key }}: {{ tpl $a_val $ | quote }}
    {{- end }}
spec:
  # Custom TLS
  {{- if $i_val.tls }}
  tls:
    - hosts:
      - {{ default (include "apps-generic-chart.hostname" (dict "Suffix" $i_key "Ingress" $i_val "Root" $)) $i_val.host }}
      secretName: {{ default (printf "%s-certificate" $.Release.Name) $i_val.secretName }}
    # Range thru extra hosts per in same ingress
    {{- if $i_val.hosts }}
    {{- range $host_key, $host_value := $i_val.hosts }}
    - hosts:
      - {{ $host_value.host }}
      secretName: {{ default (printf "%s-certificate-%d" $.Release.Name $host_key) $host_value.secretName }}
    {{- end }}
    {{- end }}
    # End Of TLS

  {{- end }}
  # Rules
  rules:
    - host: {{ default (include "apps-generic-chart.hostname" (dict "Suffix" $i_key "Ingress" $i_val "Root" $)) $i_val.host }}
      http:
        paths:
          - path: {{ default "/" $i_val.path }}
            backend:
              serviceName: {{ include "apps-generic-chart.fullname" $ }}
              servicePort: {{ $i_val.port }}
  {{- if $i_val.hosts }}
  {{- range $i_val.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - path: {{ default "/" .path }}
            backend:
              serviceName: {{ default (include "apps-generic-chart.fullname" $) .serviceName }}
              servicePort: {{ default $i_val.port .port }}
  {{- end }}
  {{- end }}
  # End Of Rules

{{- end }}
{{- end }}
