apiVersion: v1
kind: Service
metadata:
  name: {{ template "apps-generic-chart.fullname" . }}
  labels:
    app: {{ template "apps-generic-chart.name" . }}
    chart: {{ template "apps-generic-chart.chart" . }}
    release: {{ .Release.Name }}
    release-revision: {{ .Release.Revision | quote }}
    {{- if .Values.branch }}
    branch: {{ .Values.branch | quote }}
    {{- end }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIp }}
  clusterIP: {{ .Values.service.clusterIp }}
  {{- end }}
  ports:
  {{- if .Values.container.ports }}
  {{- range .Values.container.ports }}
    - port: {{ .servicePort }}
      name: {{ .name }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ template "apps-generic-chart.name" . }}
    release: {{ .Release.Name }}
