apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
  annotations:
    linkerd.io/inject: enabled
  
spec:
  selector:
    matchLabels:
      app: myapp
      instance: stable
  replicas: 10
  template:
    metadata:    
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: myapp
        instance: stable
    spec:
      containers:
      - name: myapp
        image: liammoat/canary-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
        - containerPort: 8080
