apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-canary
spec:
  selector:
    matchLabels:
      app: myapp-canary
  replicas: 0
  template:
    metadata:
      labels:
        app: myapp-canary
    spec:
      containers:
      - name: myapp-canary
        image: lmregistryacr.azurecr.io/canary-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
        - containerPort: 8080
