apiVersion: apps/v1
kind: Deployment
metadata:  
  name: myapp-canary
  labels:
    app: myapp
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    matchLabels:
      app: myapp
      instance: canary
  replicas: 0
  template:
    metadata:
      labels:
        app: myapp
        instance: canary
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: myapp-canary
        image: liammoat/canary-app:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
        - containerPort: 8080
