apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp
  # namespace: canary-native
  labels:
    release: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  # namespaceSelector:
  #   - canary-native
  #   any: true
  endpoints:
  - port: metrics